---
name: Build

on:
  pull_request:
    branches:
      - master

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

        # python version is defined in .python-version file
      - name: Set up Python
        uses: actions/setup-python@v4

      - uses: dciborow/action-pylint@0.0.7
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          reporter: github-pr-check
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with warning.
          level: warning
          glob_pattern: "**/*.py"
