---
name: Release

on:
  push:
    branches:
      - master
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

        # python version is defined in .python-version file
      - uses: actions/setup-python@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          branch: master
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
            semantic-release-pypi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PYPI_TOKEN: ${{ secrets.TIMEGREP_PYPI_TOKEN }}
